### ISSUE TITLE
Багато слів немає в словнику.

### ISSUE THREAD

**Issue by mikhalko** [asivokon/ukrainian-word-stress-dictionary#1]
Багато слів немає в словнику.

Наприклад, немає слова "хутко". Хоча є інші, де логіка? 
хутка́
хутке́
хутки́й
хутки́м
хутки́ми
хутки́х
хуткі́
хуткі́й
хуткі́м
хуткі́ша
хуткі́ше
хуткі́ший
хуткі́шим
хуткі́шими
хуткі́ших
хуткі́ші
хуткі́шій
хуткі́шім
хуткі́шого
хуткі́шої
хуткі́шому
хуткі́шою
хуткі́шу
хутко́го
хутко́ї
хутко́му
хутко́ю
хутку́

**Comment by osyvokon** [comment]
Дякую, що звернули на це увагу. Хиба парсера призвела до деяких пропущених слів. Пізніше виправлю.

**Comment by osyvokon** [comment]
Це та багато інших пропущених слів додано в #2
